---
output: 
  pdf_document:
   fig_caption: false
   includes: 
     in_header: factsheet_template_header.tex
geometry: margin=0.75cm
fontsize: 11pt  
df_print: kable
params: 
  draft: FALSE
  pages: 2
  aq_num: 0
---


```{r, include = FALSE}
# Set some knitr options 
# - We never want to show code, so echo = FALSE
knitr::opts_chunk$set(echo = FALSE)
```

```{r data}
# Regarding document type
p1 <- "factsheet_template_p1.Rmd"
p2 <- "factsheet_template_p2.Rmd"
p3 <- "factsheet_template_p3.Rmd"

aq_num <- as.numeric(params$aq_num)
```




```{r setup, include = FALSE}
library(readr)
library(readxl)
library(stringr)
library(dplyr)
library(tidyr)
library(knitr)
library(kableExtra)

aq_num_ch <- sprintf("%04d", aq_num)

aquifer <- read_csv("../out/aquifer_table.csv") %>%
  filter(aquifer_id %in% aq_num) %>%
  mutate_all(funs(str_replace_all(., c("\\&" = "\\\\&", "\\#" = "\\\\#")))) # Escape & symbols

title <- aquifer$aquifer_name
if(title == "" | title == aq_num_ch | title == aq_num | is.na(title)) {
  #title <- "No local name currently assigned"
  title <- ""
}
ow <- read_csv("../out/aquifer_ow.csv") %>%
  filter(aquifer_id %in% aq_num) %>%
  arrange(ow_status, ow) %>%
  mutate(ow_ch = sprintf("%04d", ow),
         format = case_when(ow_status == "Active" ~ paste0("\\textbf{", ow, "}"),
                            TRUE ~ as.character(ow)))
if(nrow(ow) > 20) {
  ow <- ow[1:20,]
  ow$format[20] <- "..."
}

wells_db <- read_csv("../out/wells_table.csv") %>%
  filter(aquifer_id %in% aq_num)

# Aquifer description
desc <- paste0("\\textbf{Aquifer Description} ",
               "(\\link{https://s3.ca-central-1.amazonaws.com/aquifer-docs/",   # Main site
               sprintf("%05d", round_any(aq_num, 100, f = floor)),              # Folder rounded to lower 100
               "/AQ_",                                                          # Prefix
               sprintf("%05d", aq_num),                                         # Aq number with 5 digits
               "_Aquifer_Mapping_Report.pdf}",                                  # Suffix  
               "{\\textbf{Mapping Report - ", aquifer$mapping_year, "}}):\\\\",
               str_replace(aquifer$description, ".$", ""), # Replace the trailing period with nothing
               " (subtype = ", aquifer$aquifer_subtype_code, ").")

# Link to factsheet pdf
aq_link <- paste0("https://s3.ca-central-1.amazonaws.com/aquifer-docs/", 
                  sprintf("%05d", round_any(aq_num, 100, f = floor)), 
                  "/AQ\\_", 
                  sprintf("%05d", aq_num), 
                  "\\_Aquifer\\_Factsheet.pdf")

aq_title <- paste0("\\titlelink{https://apps.nrs.gov.bc.ca/gwells/aquifers/", aq_num, "}{Aquifer \\#", aq_num, "}")


# Note that ~ (below) means a non-breaking space, which forces the tables to use a different spot to wrap the text
aquifer <- aquifer %>%
  mutate(ow = case_when(nrow(ow) > 0 ~ paste0(ow$format, collapse = ", "),
                        TRUE ~ "None")) %>%
  mutate(size_km2 = replace(size_km2, 
                            size_km2 != "Unknown",
                            paste(size_km2, "km\\textsuperscript{2}")),
         n_licences = replace(n_licences, n_licences == 0, "Unknown")) %>%
  select(`Region` = region, 
         `Water District` = water_district, 
         `Aquifer Area` = size_km2,
         `No. Wells Correlated to Aquifer` = reported_no_wells,
         `Vulnerability to Contamination` = vulnerability,
         `Productivity` = productivity,
         `Aquifer Classification` = aquifer_classification,
         `Hydraulic~Connectivity\\textsuperscript{1}` = hydraulic_connectivity,
         `Aquifer Stress Index` = aquifer_pumping_stress_index,
         `No. Water Licences Issued~to~Wells` = n_licences,
         `Observation Wells (\\footnotesize{\\textbf{Active},~Inactive})` = .data$ow) %>%
  mutate_if(is.na, ~ "Unknown")

# Add hyperlinks
aquifer <- aquifer %>%
  rename(`\\link{http://www.bclaws.ca/civix/document/id/complete/statreg/38_2016}{Water District}` = `Water District`,
         `\\link{http://www.env.gov.bc.ca/wsd/plan_protect_sustain/groundwater/aquifers/reports/aquifer_maps.pdf\\#page=16}{Vulnerability to Contamination}` = `Vulnerability to Contamination`,
         `\\link{http://www.env.gov.bc.ca/wsd/plan_protect_sustain/groundwater/aquifers/reports/aquifer_maps.pdf\\#page=19}{Productivity}` = `Productivity`,
         `\\link{http://www.env.gov.bc.ca/wsd/plan_protect_sustain/groundwater/aquifers/reports/aquifer_maps.pdf\\#page=15}{Aquifer Classification}` = `Aquifer Classification`,
         `\\link{http://a100.gov.bc.ca/appsdata/acat/documents/r50832/HydraulicConnectMW3_1474311684426_4310694949.pdf}{Hydraulic~Connectivity\\textsuperscript{1}}` = `Hydraulic~Connectivity\\textsuperscript{1}`,
         `\\link{http://governmentofbc.maps.arcgis.com/home/webmap/viewer.html?webmap=6c137fb01a364ee699440a28619e45c2}{Aquifer Stress Index}` = `Aquifer Stress Index`)

# Transform for factsheet
aquifer <- aquifer %>%
  gather(Name, Data)

```


```{r figures, include = FALSE}
# Create a list of all the figures to include
figures_p1 <- list()

# Page 1
figures_p1$map <- list.files("../figures/maps/", pattern = paste0("Aquifer_Map_", aq_num_ch, ".pdf"), full.names = TRUE)
figures_p1$water_depth <- list.files("../out/boxplots/", pattern = paste0("water_depth_", aq_num_ch, ".jpg"), full.names = TRUE)
figures_p1$well_yield <- list.files("../out/boxplots/", pattern = paste0("yield_", aq_num_ch, ".jpg"), full.names = TRUE)
figures_p1$well_depth <- list.files("../out/boxplots/", pattern = paste0("well_depth_", aq_num_ch, ".jpg"), full.names = TRUE)

# Replace empty figures with NA plots
if(length(figures_p1$map) == 0) figures_p1$map <- "../figures/maps/NA.png"
if(length(figures_p1$water_depth) == 0) figures_p1$water_depth <- "../out/boxplots/water_depth_NA.jpg"
if(length(figures_p1$well_yield) == 0) figures_p1$well_yield <- "../out/boxplots/yield_NA.jpg"
if(length(figures_p1$well_depth) == 0) figures_p1$well_depth <- "../out/boxplots/well_depth_NA.jpg"

# Page 2
# Only active wells
ow <- filter(ow, ow_status == "Active") 

if(nrow(ow) > 0) {
  figures_p2 <- tibble(a = rep(aq_num_ch, 3*nrow(ow)), ow = rep(ow$ow_ch, 3), 
                       type = sort(rep(c("combo", "trend", "piper"), length(ow)/3))) %>%
    mutate(fig = case_when(type == "combo" ~ paste0("../out/gwl/combo_", a, "_OW", .data$ow, ".png"),
                           type == "trend" ~ paste0("../out/trends/trends_", a, "_OW", .data$ow, ".png"),
                           type == "piper" ~ paste0("../figures/piperplots/Piperplot_", a, "_OW", .data$ow, ".jpg")),
           exists = file.exists(fig),
           fig = replace(fig, !exists, paste0("../figures/na/figure_missing_", type[!exists], ".png"))) %>%
    group_by(.data$ow) %>%
    mutate(missing = sum(!exists)) %>%
    filter(missing != 3) %>%
    select(-exists, -missing)
  
  # Omit well if missing all figures
  for(o in unique(figures_p2$ow)) {
    if(all(str_detect(figures_p2$fig[figures_p2$ow == o], "figure_missing"))) {
      figures_p2 <- filter(figures_p2, .data$ow != o)
    }
  }
  
  # Get Piper text for each obs well and add link
  piper_text <- read_excel("../data/piper_text.xlsx", sheet = 1) %>%
    rename_all(tolower) %>%
    mutate(hydrogeochemistry = paste0(hydrogeochemistry,
                                     " \\link{https://a100.gov.bc.ca/pub/ems/mainmenu.do?",
                                     "userAction=monitoringLocationsCriteria&bean.p_mon_locn_id=", ems_id, 
                                     "}{For EMS water chemistry data, EMSID ", ems_id, "}."))
  
  
} else {
  figures_p2 <- tibble()
}

# Page 3
extra <- read_excel("../data/extra_page_images.xlsx") %>%
  separate_rows(aquifer_ids, sep = ",", convert = TRUE) %>%
  filter(aq_num == aquifer_ids) %>%
  left_join(read_excel("../data/extra_page_index.xlsx"), by = "type") %>%
  arrange(order, image) %>%
  distinct() #in case of duplicates

```
  
  
```{r create_page1, results = "asis"}
cat(knit_child(p1))
```


```{r create_page2s, eval = nrow(figures_p2) > 0 & params$pages >= 2, results = "asis", message = FALSE}
# Get obs wells from figure names
obs_wells <- sort(unique(figures_p2$ow))


if(length(obs_wells) > 0) {
  wells <- wells_db %>%
    filter(ow %in% as.numeric(obs_wells))
}

out <- NULL
for (o in obs_wells) {
  f <- filter(figures_p2, .data$ow == o) %>%
    spread(type, fig)
  
  # Run through p2 template
  ow <- as.numeric(as.numeric(str_extract(o, "[0-9]{4}")))
  
  # Get piper text
  p_text <- piper_text$hydrogeochemistry[piper_text$obs_well == ow]
  
  cat("\\newpage")
  cat(knit_child(p2))
}
```

  
```{r create_page3, eval = nrow(extra) > 0 & params$pages >=3, results = "asis", message = FALSE}

for(i in seq(1, nrow(extra), 2)) {
  e <- slice(extra, i:(i+1)) %>%
    mutate(image = file.path("../figures/extra", image))
  cat("\\newpage")
  cat(knit_child(p3))
}
```
